"""add_version_to_products

Revision ID: eeda354a06d5
Revises: a6857ee46e33
Create Date: 2026-01-10 18:08:42.209200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eeda354a06d5"
down_revision: Union[str, Sequence[str], None] = "a6857ee46e33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("version", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "version")
    # ### end Alembic commands ###
